stages:
  - deploy

variables:
  ANSIBLE_VERSION: "2.14.0" # Update to the required Ansible versions
  AWS_REGION: "us-east-1"

before_script:
  # Install dependencies
  - apt-get update -qq
  - apt-get install -qq -y software-properties-common
  - apt-add-repository --yes --update ppa:ansible/ansible
  - apt-get install -qq -y ansible=${ANSIBLE_VERSION} python3-boto3 python3-botocore

  # Install AWS Ansible collection
  - ansible-galaxy collection install amazon.aws

  # Configure AWS credentials
  - mkdir -p ~/.aws
  - echo "[default]" > ~/.aws/credentials
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

deploy:
  stage: deploy
  script:
    - cd ansible
    - ansible-playbook -i inventory/aws_ec2.yaml playbook.yml
  environment:
    name: production
