---
- name: Deploy Jenkins to Dynamic EC2 Instances
  hosts: all
  become: true

  vars:
  #   ansible_ssh_private_key_file: C:/Users/clovi/OneDrive\Documents/all-my-jobs/ansible-dynamic/virginia.pem
      # ansible_connection: local
     aws_access_key: 
     aws_secret_key: 
     ansible_python_interpreter: "{{ ansible_playbook_python }}"
     ssh_key_path: ~/put key name here
    #  java_packages:
    #   - openjdk-11-jdk
    #  ssh_key_content: |
    #   -----BEGIN OPENSSH PRIVATE KEY-----
    #   [PASTE-YOUR-PRIVATE-KEY-HERE]
    #   -----END OPENSSH PRIVATE KEY-----

  tasks:
    # - name: Install Java
    #   yum:
    #     name: java-1.8.0-openjdk
    #     state: present
    - name: Enable Amazon Linux extras for Java
      command: amazon-linux-extras enable java-openjdk11

    - name: Install Java 8
      yum:
        name: java-1.8.0-openjdk
        state: present


    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: http://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes