version: '3.8'

services:
  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # environment:
    #   - REACT_APP_BACKEND_URL=http://backend:8800

  backend:
    build:
      context: /backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"

